BEGIN

INSERT INTO JIT_MOVE_TRADE_HEADER  
( 
  EXTERNAL_ID,
  EXTERNAL_NO,
  WH_NAME,
  TRADE_TYPE,
  FROM_STORER,
  TO_STORER,
  APPLY_DATE,
  REF_NO,
  REMARK
)
SELECT DISTINCT
  TRX_PO.PO_HEADER_ID AS ExternalId,
  TRX_PO.PO_NO AS ExternalNo,
  'GT' AS WhName,
  'tran' AS TradeType,
  TRX_SO.STORER_SELLER AS FromStorer,
  TRX_PO.STORER_BUYER AS ToStorer,
  CURRENT_TIMESTAMP AS ApplyDate,
  TRX_SO.ORDER_NUMBER AS RefNo,
  '' AS Remark
FROM 
  (SELECT MMT.TRANSACTION_ID,
    MMT.ORGANIZATION_ID, MMT.TRANSACTION_DATE, MMT.TRANSACTION_QUANTITY IN_QTY,
    MMT.SOURCE_CODE, MMT.TRANSACTION_SOURCE_ID AS PO_HEADER_ID,
    PH.SEGMENT1 AS PO_NO,
    ZRPC.ORGANIZATION_ID_S,
    ZRPC.CUST_ID,
    MSI.SEGMENT1 AS PO_ITEM,
    DECODE(MIL.SEGMENT1, '', '', (MIL.SEGMENT1 || '.' || MIL.SEGMENT2)) AS PO_IN_SUB,
    ZRPC.STORER_BUYER
  FROM MTL_MATERIAL_TRANSACTIONS@PROD2 MMT,
       PO_HEADERS_ALL@PROD2 PH,
       MTL_SYSTEM_ITEMS_B@PROD2 MSI,
       MTL_ITEM_LOCATIONS@PROD2 MIL,
       ZEN_REALATED_PARTYS_SET_CODE@PROD2 ZRPC
  WHERE MMT.SOURCE_CODE = 'RCV'
    AND MMT.TRANSACTION_TYPE_ID = 18
    AND MMT.ORGANIZATION_ID = 169 
    AND MMT.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID 
    AND MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
    AND MMT.ORGANIZATION_ID = MIL.ORGANIZATION_ID(+) 
    AND MMT.SUBINVENTORY_CODE = MIL.SUBINVENTORY_CODE(+)
    AND MMT.LOCATOR_ID = MIL.INVENTORY_LOCATION_ID(+)
    AND MMT.SUBINVENTORY_CODE = '外存倉'
    AND (MIL.SEGMENT1 LIKE '%基通%' OR MIL.SEGMENT2 LIKE '%基通%')
    AND MIL.ATTRIBUTE3 = 'JIT'
    AND MMT.ORGANIZATION_ID = ZRPC.ORGANIZATION_ID_P
    AND PH.VENDOR_ID = ZRPC.VENDOR_ID
    AND PH.VENDOR_SITE_ID = ZRPC.VENDOR_SITE_ID
    AND MMT.TRANSACTION_SOURCE_ID = PH.PO_HEADER_ID 
    AND TRUNC(MMT.TRANSACTION_DATE) = TRUNC(SYSDATE)
  ) TRX_PO,
  (
    SELECT OH.SOLD_TO_ORG_ID, OH.CUST_PO_NUMBER, OH.ORDER_NUMBER||'.'||OTTL.NAME AS ORDER_NUMBER,
           MSI.SEGMENT1 AS SO_ITEM,
           MMT.TRANSACTION_QUANTITY OUT_QTY,
           DECODE(MIL.SEGMENT1, '', '', (MIL.SEGMENT1 || '.' || MIL.SEGMENT2)) AS SO_OUT_SUB,
           ZRPC.STORER_SELLER
    FROM MTL_MATERIAL_TRANSACTIONS@PROD2 MMT,
         MTL_SYSTEM_ITEMS_B@PROD2 MSI,
         MTL_ITEM_LOCATIONS@PROD2 MIL,
         OE_ORDER_HEADERS_ALL@PROD2 OH,
         ZEN_REALATED_PARTYS_SET_CODE@PROD2 ZRPC,
         OE_TRANSACTION_TYPES_TL@PROD2 OTTL 
    WHERE MMT.TRANSACTION_TYPE_ID = 33
      AND MMT.ORGANIZATION_ID = 209 
      AND MMT.TRANSACTION_REFERENCE = OH.HEADER_ID
      AND MMT.ORGANIZATION_ID = ZRPC.ORGANIZATION_ID_S
      AND MMT.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID 
      AND MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
      AND MMT.ORGANIZATION_ID = MIL.ORGANIZATION_ID(+) 
      AND MMT.SUBINVENTORY_CODE = MIL.SUBINVENTORY_CODE(+)
      AND MMT.LOCATOR_ID = MIL.INVENTORY_LOCATION_ID(+) 
      AND OH.ORDER_TYPE_ID = OTTL.TRANSACTION_TYPE_ID
      AND MMT.SUBINVENTORY_CODE = '外存倉'
      AND (MIL.SEGMENT1 LIKE '%基通%' OR MIL.SEGMENT2 LIKE '%基通%')
      AND MIL.ATTRIBUTE3 = 'JIT'
      AND OH.SOLD_TO_ORG_ID = ZRPC.CUST_ID
    
    UNION
    
    SELECT OH.SOLD_TO_ORG_ID, OH.CUST_PO_NUMBER, OH.ORDER_NUMBER||'.'||OTTL.NAME AS ORDER_NUMBER,
           MSI.SEGMENT1 AS SO_ITEM,
           MMT.TRANSACTION_QUANTITY OUT_QTY,
           'SHC基通.IT',
           ZRPC.STORER_SELLER
    FROM MTL_MATERIAL_TRANSACTIONS@JY MMT,
         MTL_SYSTEM_ITEMS_B@JY MSI,
         MTL_ITEM_LOCATIONS@JY MIL,
         OE_ORDER_HEADERS_ALL@JY OH,
         OE_ORDER_LINES_ALL@JY OL,
         ZEN_REALATED_PARTYS_SET_CODE@PROD2 ZRPC,
         OE_TRANSACTION_TYPES_TL@JY OTTL 
    WHERE MMT.TRANSACTION_TYPE_ID = 52
      AND MMT.ORGANIZATION_ID = 371 
      AND MMT.TRANSACTION_QUANTITY < 0 
      AND OL.HEADER_ID = OH.HEADER_ID 
      AND OL.ORG_ID = OH.ORG_ID 
      AND MMT.TRX_SOURCE_LINE_ID = OL.LINE_ID 
      AND MMT.ORGANIZATION_ID = ZRPC.ORGANIZATION_ID_S
      AND MMT.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID 
      AND MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
      AND MMT.ORGANIZATION_ID = MIL.ORGANIZATION_ID(+) 
      AND MMT.SUBINVENTORY_CODE = MIL.SUBINVENTORY_CODE(+)
      AND MMT.LOCATOR_ID = MIL.INVENTORY_LOCATION_ID(+) 
      AND OH.ORDER_TYPE_ID = OTTL.TRANSACTION_TYPE_ID
      AND MMT.SUBINVENTORY_CODE = '外存倉'
      AND (MIL.SEGMENT1 LIKE '%基通%' OR MIL.SEGMENT2 LIKE '%基通%')
      AND MIL.ATTRIBUTE3 = 'JIT'
      AND OH.SOLD_TO_ORG_ID = ZRPC.CUST_ID
    
    UNION
    
    SELECT OH.SOLD_TO_ORG_ID, OH.CUST_PO_NUMBER, OH.ORDER_NUMBER||'.'||OTTL.NAME AS ORDER_NUMBER,
           MSI.SEGMENT1 AS SO_ITEM,
           MMT.TRANSACTION_QUANTITY OUT_QTY,
           'SHC基通.IT',
           ZRPC.STORER_SELLER
    FROM MTL_MATERIAL_TRANSACTIONS@SHCTRADING0 MMT,
         MTL_SYSTEM_ITEMS_B@SHCTRADING0 MSI,
         MTL_ITEM_LOCATIONS@SHCTRADING0 MIL,
         OE_ORDER_HEADERS_ALL@SHCTRADING0 OH,
         OE_ORDER_LINES_ALL@SHCTRADING0 OL,
         ZEN_REALATED_PARTYS_SET_CODE@PROD2 ZRPC,
         OE_TRANSACTION_TYPES_TL@SHCTRADING0 OTTL 
    WHERE MMT.TRANSACTION_TYPE_ID = 52
      AND MMT.ORGANIZATION_ID = 209 
      AND MMT.TRANSACTION_QUANTITY < 0 
      AND OL.HEADER_ID = OH.HEADER_ID 
      AND OL.ORG_ID = OH.ORG_ID 
      AND MMT.TRX_SOURCE_LINE_ID = OL.LINE_ID 
      AND MMT.ORGANIZATION_ID = ZRPC.ORGANIZATION_ID_S
      AND MMT.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID 
      AND MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
      AND MMT.ORGANIZATION_ID = MIL.ORGANIZATION_ID(+) 
      AND MMT.SUBINVENTORY_CODE = MIL.SUBINVENTORY_CODE(+)
      AND MMT.LOCATOR_ID = MIL.INVENTORY_LOCATION_ID(+) 
      AND OH.ORDER_TYPE_ID = OTTL.TRANSACTION_TYPE_ID
      AND MMT.SUBINVENTORY_CODE = '外存倉'
      AND (MIL.SEGMENT1 LIKE '%基通%' OR MIL.SEGMENT2 LIKE '%基通%')
      AND MIL.ATTRIBUTE3 = 'JIT'
      AND OH.SOLD_TO_ORG_ID = ZRPC.CUST_ID
  ) TRX_SO 
WHERE TRX_PO.PO_NO = TRX_SO.CUST_PO_NUMBER
  AND TRX_PO.PO_ITEM = TRX_SO.SO_ITEM 
  AND NOT EXISTS (
    SELECT 1
    FROM JIT_MOVE_TRADE_HEADER JMTH
    WHERE JMTH.EXTERNAL_ID = TRX_PO.PO_HEADER_ID
  );

INSERT INTO JIT_MOVE_TRADE_LINE
( 
  HEADER_ID,
  SKU,
  QTY,
  FROM_STORER_CATE,
  TO_STORER_CATE,
  REMARK,
  MF_SKU
)
SELECT JMTH.HEADER_ID,
       TRX_PO.PO_ITEM,
       TRX_PO.IN_QTY,
       TRX_SO.SO_OUT_SUB,
       TRX_PO.PO_IN_SUB,
       NULL,
       TRX_SO.MF_SKU
FROM 
  (SELECT MMT.ORGANIZATION_ID, MMT.TRANSACTION_DATE, MMT.TRANSACTION_QUANTITY IN_QTY,
    MMT.SOURCE_CODE, MMT.TRANSACTION_SOURCE_ID,
    PH.SEGMENT1 AS PO_NO,
    ZRPC.ORGANIZATION_ID_S,
    ZRPC.CUST_ID,
    MSI.SEGMENT1 AS PO_ITEM,
    DECODE(MIL.SEGMENT1, '', '', (MIL.SEGMENT1 || '.' || MIL.SEGMENT2)) AS PO_IN_SUB,
    MSI.SEGMENT1 AS MF_SKU
  FROM MTL_MATERIAL_TRANSACTIONS@PROD2 MMT,
       PO_HEADERS_ALL@PROD2 PH,
       MTL_SYSTEM_ITEMS_B@PROD2 MSI,
       MTL_ITEM_LOCATIONS@PROD2 MIL,
       ZEN_REALATED_PARTYS_SET_CODE@PROD2 ZRPC
  WHERE MMT.SOURCE_CODE = 'RCV'
    AND MMT.TRANSACTION_TYPE_ID = 18 
    AND MMT.ORGANIZATION_ID = 169 
    AND MMT.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID 
    AND MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
    AND MMT.ORGANIZATION_ID = MIL.ORGANIZATION_ID(+) 
    AND MMT.SUBINVENTORY_CODE = MIL.SUBINVENTORY_CODE(+)
    AND MMT.LOCATOR_ID = MIL.INVENTORY_LOCATION_ID(+)
    AND MMT.SUBINVENTORY_CODE = '外存倉'
    AND (MIL.SEGMENT1 LIKE '%基通%' OR MIL.SEGMENT2 LIKE '%基通%')
    AND MIL.ATTRIBUTE3 = 'JIT'
    AND MMT.ORGANIZATION_ID = ZRPC.ORGANIZATION_ID_P
    AND PH.VENDOR_ID = ZRPC.VENDOR_ID
    AND PH.VENDOR_SITE_ID = ZRPC.VENDOR_SITE_ID
    AND MMT.TRANSACTION_SOURCE_ID = PH.PO_HEADER_ID
    AND TRUNC(MMT.TRANSACTION_DATE) = TRUNC(SYSDATE)
  ) TRX_PO,
  (
    SELECT OH.SOLD_TO_ORG_ID, OH.CUST_PO_NUMBER, OH.ORDER_NUMBER||'.'||OTTL.NAME AS ORDER_NUMBER,
           MSI.SEGMENT1 AS SO_ITEM,
           MMT.TRANSACTION_QUANTITY OUT_QTY,
           DECODE(MIL.SEGMENT1, '', '', (MIL.SEGMENT1 || '.' || MIL.SEGMENT2)) AS SO_OUT_SUB,
           ZRPC.STORER_SELLER,
           MSI.SEGMENT1 AS MF_SKU
    FROM MTL_MATERIAL_TRANSACTIONS@PROD2 MMT,
         MTL_SYSTEM_ITEMS_B@PROD2 MSI,
         MTL_ITEM_LOCATIONS@PROD2 MIL,
         OE_ORDER_HEADERS_ALL@PROD2 OH,
         ZEN_REALATED_PARTYS_SET_CODE@PROD2 ZRPC,
         OE_TRANSACTION_TYPES_TL@PROD2 OTTL 
    WHERE MMT.TRANSACTION_TYPE_ID = 33
      AND MMT.ORGANIZATION_ID = 209 
      AND MMT.TRANSACTION_REFERENCE = OH.HEADER_ID
      AND MMT.ORGANIZATION_ID = ZRPC.ORGANIZATION_ID_S
      AND MMT.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID 
      AND MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
      AND MMT.ORGANIZATION_ID = MIL.ORGANIZATION_ID(+) 
      AND MMT.SUBINVENTORY_CODE = MIL.SUBINVENTORY_CODE(+)
      AND MMT.LOCATOR_ID = MIL.INVENTORY_LOCATION_ID(+) 
      AND OH.ORDER_TYPE_ID = OTTL.TRANSACTION_TYPE_ID
      AND MMT.SUBINVENTORY_CODE = '外存倉'
      AND (MIL.SEGMENT1 LIKE '%基通%' OR MIL.SEGMENT2 LIKE '%基通%')
      AND MIL.ATTRIBUTE3 = 'JIT'
      AND OH.SOLD_TO_ORG_ID = ZRPC.CUST_ID
    
    UNION
    
    SELECT OH.SOLD_TO_ORG_ID, OH.CUST_PO_NUMBER, OH.ORDER_NUMBER||'.'||OTTL.NAME AS ORDER_NUMBER,
           MSI.SEGMENT1 AS SO_ITEM,
           MMT.TRANSACTION_QUANTITY OUT_QTY,
           'SHC基通.IT',
           ZRPC.STORER_SELLER,
           NVL(NVL(OL.ATTRIBUTE16,ZEN_GET_WMS_ITEM_F(MSI.SEGMENT1)),MSI.SEGMENT1) AS MF_SKU
    FROM MTL_MATERIAL_TRANSACTIONS@JY MMT,
         MTL_SYSTEM_ITEMS_B@JY MSI,
         MTL_ITEM_LOCATIONS@JY MIL,
         OE_ORDER_HEADERS_ALL@JY OH,
         OE_ORDER_LINES_ALL@JY OL,
         ZEN_REALATED_PARTYS_SET_CODE@PROD2 ZRPC,
         OE_TRANSACTION_TYPES_TL@JY OTTL 
    WHERE MMT.TRANSACTION_TYPE_ID = 52
      AND MMT.ORGANIZATION_ID = 371 
      AND MMT.TRANSACTION_QUANTITY < 0 
      AND OL.HEADER_ID = OH.HEADER_ID 
      AND OL.ORG_ID = OH.ORG_ID 
      AND MMT.TRX_SOURCE_LINE_ID = OL.LINE_ID 
      AND MMT.ORGANIZATION_ID = ZRPC.ORGANIZATION_ID_S
      AND MMT.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID 
      AND MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
      AND MMT.ORGANIZATION_ID = MIL.ORGANIZATION_ID(+) 
      AND MMT.SUBINVENTORY_CODE = MIL.SUBINVENTORY_CODE(+)
      AND MMT.LOCATOR_ID = MIL.INVENTORY_LOCATION_ID(+) 
      AND OH.ORDER_TYPE_ID = OTTL.TRANSACTION_TYPE_ID
      AND MMT.SUBINVENTORY_CODE = '外存倉'
      AND (MIL.SEGMENT1 LIKE '%基通%' OR MIL.SEGMENT2 LIKE '%基通%')
      AND MIL.ATTRIBUTE3 = 'JIT'
      AND OH.SOLD_TO_ORG_ID = ZRPC.CUST_ID
    
    UNION
    
    SELECT OH.SOLD_TO_ORG_ID, OH.CUST_PO_NUMBER, OH.ORDER_NUMBER||'.'||OTTL.NAME AS ORDER_NUMBER,
           MSI.SEGMENT1 AS SO_ITEM,
           MMT.TRANSACTION_QUANTITY OUT_QTY,
           'SHC基通.IT',
           ZRPC.STORER_SELLER,
           NVL(NVL(OL.ATTRIBUTE16,ZEN_GET_WMS_ITEM_F(MSI.SEGMENT1)),MSI.SEGMENT1) AS MF_SKU
    FROM MTL_MATERIAL_TRANSACTIONS@SHCTRADING0 MMT,
         MTL_SYSTEM_ITEMS_B@SHCTRADING0 MSI,
         MTL_ITEM_LOCATIONS@SHCTRADING0 MIL,
         OE_ORDER_HEADERS_ALL@SHCTRADING0 OH,
         OE_ORDER_LINES_ALL@SHCTRADING0 OL,
         ZEN_REALATED_PARTYS_SET_CODE@PROD2 ZRPC,
         OE_TRANSACTION_TYPES_TL@SHCTRADING0 OTTL 
    WHERE MMT.TRANSACTION_TYPE_ID = 52
      AND MMT.ORGANIZATION_ID = 209 
      AND MMT.TRANSACTION_QUANTITY < 0 
      AND OL.HEADER_ID = OH.HEADER_ID 
      AND OL.ORG_ID = OH.ORG_ID 
      AND MMT.TRX_SOURCE_LINE_ID = OL.LINE_ID 
      AND MMT.ORGANIZATION_ID = ZRPC.ORGANIZATION_ID_S
      AND MMT.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID 
      AND MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
      AND MMT.ORGANIZATION_ID = MIL.ORGANIZATION_ID(+) 
      AND MMT.SUBINVENTORY_CODE = MIL.SUBINVENTORY_CODE(+)
      AND MMT.LOCATOR_ID = MIL.INVENTORY_LOCATION_ID(+) 
      AND OH.ORDER_TYPE_ID = OTTL.TRANSACTION_TYPE_ID
      AND MMT.SUBINVENTORY_CODE = '外存倉'
      AND (MIL.SEGMENT1 LIKE '%基通%' OR MIL.SEGMENT2 LIKE '%基通%')
      AND MIL.ATTRIBUTE3 = 'JIT'
      AND OH.SOLD_TO_ORG_ID = ZRPC.CUST_ID
  ) TRX_SO,
  JIT_MOVE_TRADE_HEADER JMTH
WHERE TRX_PO.PO_NO = TRX_SO.CUST_PO_NUMBER
  AND TRX_PO.PO_ITEM = TRX_SO.SO_ITEM
  AND TRX_PO.TRANSACTION_SOURCE_ID = JMTH.EXTERNAL_ID
  AND TRX_PO.PO_NO = JMTH.EXTERNAL_NO
  AND JMTH.STATUS = 'PENDING'
  AND NOT EXISTS (
    SELECT 1
    FROM JIT_MOVE_TRADE_LINE JMTL
    WHERE JMTH.HEADER_ID = JMTL.HEADER_ID
  );

END;