BEGIN
INSERT INTO JIT_MOVE_TRADE_HEADER
(
    external_id,
    external_no,
    wh_name,
    trade_type,
    from_storer,
    to_storer,
    apply_date,
    ref_no,
    remark
)
SELECT DISTINCT
    ZMTH.HEADER_ID AS ExternalID,
    ZMTH.REQUEST_NUMBER AS ExternalNo,
    'GT' AS WhName,
    'move' as TradeType,
    DECODE(ZMTH.ORGANIZATION_ID,169,'ZCSH','ZTSH') as FromStorer ,
    DECODE(ZMTH.ORGANIZATION_ID,169,'ZCSH','ZTSH') as ToStorer ,
    CURRENT_TIMESTAMP as ApplyDate,
    ZMTH.REQUEST_NUMBER as RefNo,
    null as remark
FROM ZEN_MTL_TXN_REQUEST_HEADERS@ZENPROD ZMTH,
     ZEN_MTL_TXN_REQUEST_LINES@ZENPROD ZMTL,
     MTL_ITEM_LOCATIONS@ZENPROD MIL ,
     MTL_ITEM_LOCATIONS@ZENPROD MIL1 ,
     MTL_MATERIAL_TRANSACTIONS@ZENPROD MMT,
     MTL_MATERIAL_TRANSACTIONS@ZENPROD MMT1,
     MTL_SYSTEM_ITEMS_B@ZENPROD MSI
WHERE  ZMTH.HEADER_ID = ZMTL.HEADER_ID
  AND ZMTH.ORGANIZATION_ID  IN (169)
  AND ZMTL.LINE_STATUS = 5
  AND ZMTH.HEADER_STATUS = 3
  AND TRUNC(MMT.TRANSACTION_DATE)= TRUNC(SYSDATE)
  AND ZMTL.ORGANIZATION_ID = MIL.ORGANIZATION_ID
  AND ZMTL.FROM_SUBINVENTORY_CODE = MIL.SUBINVENTORY_CODE
  AND ZMTL.FROM_LOCATOR_ID = MIL.INVENTORY_LOCATION_ID
  AND ZMTL.FROM_SUBINVENTORY_CODE = '外存倉'
  AND (MIL.SEGMENT1 like '%基通%' OR MIL.SEGMENT2 like '%基通%')
  AND  MIL.attribute3='JIT'
  AND ZMTL.ORGANIZATION_ID = MIL1.ORGANIZATION_ID
  AND ZMTL.TO_SUBINVENTORY_CODE = MIL1.SUBINVENTORY_CODE
  AND ZMTL.TO_LOCATOR_ID = MIL1.INVENTORY_LOCATION_ID
  AND ZMTL.TO_SUBINVENTORY_CODE = '外存倉'
  AND (MIL1.SEGMENT1 like '%基通%' OR MIL1.SEGMENT2 like '%基通%')
  AND  MIL1.attribute3='JIT'
  AND ZMTL.LINE_ID = MMT.SOURCE_LINE_ID
  AND ZMTH.REQUEST_NUMBER = MMT.SOURCE_CODE
  AND ZMTL.INVENTORY_ITEM_ID = MMT.INVENTORY_ITEM_ID
  AND ZMTL.ORGANIZATION_ID = MMT.ORGANIZATION_ID
  AND MMT.TRANSACTION_TYPE_ID = 2
  AND ZMTL.FROM_SUBINVENTORY_CODE = MMT.SUBINVENTORY_CODE
  AND ZMTL.FROM_LOCATOR_ID = MMT.LOCATOR_ID
  AND ZMTL.LINE_ID = MMT1.SOURCE_LINE_ID
  AND ZMTH.REQUEST_NUMBER = MMT1.SOURCE_CODE
  AND ZMTL.INVENTORY_ITEM_ID = MMT1.INVENTORY_ITEM_ID
  AND ZMTL.ORGANIZATION_ID = MMT1.ORGANIZATION_ID
  AND MMT.TRANSACTION_TYPE_ID = 2
  AND ZMTL.TO_SUBINVENTORY_CODE = MMT1.SUBINVENTORY_CODE
  AND ZMTL.TO_LOCATOR_ID = MMT1.LOCATOR_ID
  AND ZMTL.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
  AND ZMTL.ORGANIZATION_ID = MSI.ORGANIZATION_ID
  AND NOT EXISTS(
    SELECT 1
    FROM JIT_MOVE_TRADE_HEADER
    WHERE
        external_id = ZMTH.REQUEST_NUMBER );

INSERT INTO JIT_MOVE_TRADE_LINE
(
    header_id,
    sku,
    qty,
    from_storer_cate,
    to_storer_cate,
    lot,
    batch,
    date_code,
    coo,
    remark,
    mf_sku
)
SELECT
    jmth.header_id,
    MSI.SEGMENT1,
    ZMTL.QUANTITY,
    DECODE (mil.segment1,
            '', '',
            (mil.segment1 || '.' || mil.segment2)) as FromStorerCate,
    DECODE (mil1.segment1,
            '', '',
            (mil1.segment1 || '.' || mil1.segment2)) as ToStorerCate,
    NULL AS Lot,
    NULL AS Batch,
    NULL AS DateCode,
    NULL AS Coo,
    NULL AS Remark,
    NVL(NVL(ZMTL.VENDOR_MATERIAL_INFO,ZEN_GET_WMS_ITEM_F(MSI.SEGMENT1,ZMTH.ORGANIZATION_ID)),MSI.SEGMENT1)  AS MF_SKU
FROM ZEN_MTL_TXN_REQUEST_HEADERS@ZENPROD ZMTH,
     ZEN_MTL_TXN_REQUEST_LINES@ZENPROD ZMTL,
     MTL_ITEM_LOCATIONS@ZENPROD MIL ,
     MTL_ITEM_LOCATIONS@ZENPROD MIL1 ,
     MTL_MATERIAL_TRANSACTIONS@ZENPROD MMT,
     MTL_MATERIAL_TRANSACTIONS@ZENPROD MMT1,
     MTL_SYSTEM_ITEMS_B@ZENPROD MSI ,
     JIT_MOVE_TRADE_HEADER jmth
WHERE  ZMTH.HEADER_ID = ZMTL.HEADER_ID
  AND ZMTH.ORGANIZATION_ID  IN (169)
  AND ZMTL.LINE_STATUS = 5
  AND ZMTH.HEADER_STATUS = 3
  AND TRUNC(MMT.TRANSACTION_DATE)= TRUNC(SYSDATE)
  AND ZMTL.ORGANIZATION_ID = MIL.ORGANIZATION_ID
  AND ZMTL.FROM_SUBINVENTORY_CODE = MIL.SUBINVENTORY_CODE
  AND ZMTL.FROM_LOCATOR_ID = MIL.INVENTORY_LOCATION_ID
  AND ZMTL.FROM_SUBINVENTORY_CODE = '外存倉'
  AND (MIL.SEGMENT1 like '%基通%' OR MIL.SEGMENT2 like '%基通%')
  AND MIL.attribute3='JIT'
  AND ZMTL.ORGANIZATION_ID = MIL1.ORGANIZATION_ID
  AND ZMTL.TO_SUBINVENTORY_CODE = MIL1.SUBINVENTORY_CODE
  AND ZMTL.TO_LOCATOR_ID = MIL1.INVENTORY_LOCATION_ID
  AND ZMTL.TO_SUBINVENTORY_CODE = '外存倉'
  AND (MIL1.SEGMENT1 like '%基通%' OR MIL1.SEGMENT2 like '%基通%')
  AND  MIL1.attribute3='JIT'
  AND ZMTL.LINE_ID = MMT.SOURCE_LINE_ID
  AND ZMTH.REQUEST_NUMBER = MMT.SOURCE_CODE
  AND ZMTL.INVENTORY_ITEM_ID = MMT.INVENTORY_ITEM_ID
  AND ZMTL.ORGANIZATION_ID = MMT.ORGANIZATION_ID
  AND MMT.TRANSACTION_TYPE_ID = 2
  AND ZMTL.FROM_SUBINVENTORY_CODE = MMT.SUBINVENTORY_CODE
  AND ZMTL.FROM_LOCATOR_ID = MMT.LOCATOR_ID
  AND ZMTL.LINE_ID = MMT1.SOURCE_LINE_ID
  AND ZMTH.REQUEST_NUMBER = MMT1.SOURCE_CODE
  AND ZMTL.INVENTORY_ITEM_ID = MMT1.INVENTORY_ITEM_ID
  AND ZMTL.ORGANIZATION_ID = MMT1.ORGANIZATION_ID
  AND MMT.TRANSACTION_TYPE_ID = 2
  AND ZMTL.TO_SUBINVENTORY_CODE = MMT1.SUBINVENTORY_CODE
  AND ZMTL.TO_LOCATOR_ID = MMT1.LOCATOR_ID
  AND ZMTL.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
  AND ZMTL.ORGANIZATION_ID = MSI.ORGANIZATION_ID
  AND ZMTH.REQUEST_NUMBER = jmth.external_id
  AND jmth.status ='PENDING'
  AND NOT EXISTS(
    SELECT 1
    FROM  JIT_MOVE_TRADE_LINE
    WHERE
        header_id = jmth.header_id );
END;
