begin
EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_LANGUAGE= ''AMERICAN''';
insert into ZEN_B2B_JSON_SO_TMP (SEQ_ID,SENDER_CODE,RECEIVER_CODE,STATUS,DIRECTION,DOC_DATETIME,LAST_UPDATE_DATE,CREATION_DATE,USER_NO,ID,ORDER_NO,INV_SPLIT,INVOICE_NO,INVOICE_DATE,EXP_SHIP_DATE,CUST_NO,DEPT,CUST_NAME,INVOICE_ADDRESS,SHIP_TO_NO,DELIVERY_ADDRESS,SHIP_TO_CONTACT,SHIP_TO_PHONE,ZT_PART_NO,CUST_PART_NO,CUSTOMER_PO,SHIP_NOTICE,SHIP_NOTES,STATUS1,BRAND,QUANTITY,UNIT_PRICE,AMOUNT,CUST_PO,CUST_PO2,CUST_POLINE,CUST_PN,CUST_PN2,ITEM_DESC,ITEM_MODE,ORDER_LINE_MEMO,UNIT_WEIGHT,WEIGHT_UOM_CODE,FROM_SUBINVENTORY_CODE,SEGMENT1,SEGMENT2,KIND,SUPPLIER_PARTNO,INV_AND_PAC,CUST_PART_NO2,PO_REMARK,ORI_PO_NO,RMA_NUMBER,ORD_TYPE,QC_TYPE) 
select ZEN_B2B_JSON_SEQ.nextval,SENDER_CODE,RECEIVER_CODE,STATUS,DIRECTION,DOC_DATETIME,LAST_UPDATE_DATE,CREATION_DATE,USER_NO,ID,ORDER_NO,INV_SPLIT,INVOICE_NO,INVOICE_DATE,EXP_SHIP_DATE,CUST_NO,DEPT,CUST_NAME,INVOICE_ADDRESS,SHIP_TO_NO,DELIVERY_ADDRESS,SHIP_TO_CONTACT,SHIP_TO_PHONE,ZT_PART_NO,CUST_PART_NO,CUSTOMER_PO,SHIP_NOTICE,SHIP_NOTES,STATUS1,BRAND,QUANTITY,UNIT_PRICE,AMOUNT,CUST_PO,CUST_PO2,CUST_POLINE,CUST_PN,CUST_PN2,ITEM_DESC,ITEM_MODE,ORDER_LINE_MEMO,UNIT_WEIGHT,WEIGHT_UOM_CODE,FROM_SUBINVENTORY_CODE,SEGMENT1,SEGMENT2,KIND,SUPPLIER_PARTNO,INV_AND_PAC,CUST_PART_NO2,PO_REMARK,ORI_PO_NO,RMA_NUMBER,ORD_TYPE,QC_TYPE
from (
     
     SELECT DISTINCT
     'ZEN' as SENDER_CODE,
     'JIT' as RECEIVER_CODE,
      CASE 
        WHEN PH.SEGMENT1||'-'||PL.LINE_NUM IS NULL
        OR zprh.RETURN_DATE IS NULL
        OR PV.VENDOR_NAME IS NULL
        OR zprh.SHIP_TO_ADDRESS IS NULL
        OR zprh.SHIP_TO_CONTACT IS NULL
        OR MSI.SEGMENT1 IS NULL
        OR PVSA.VENDOR_SITE_CODE IS NULL
        OR zpr.QUANTITY IS NULL
        OR MSI.ATTRIBUTE1 IS NULL
        OR zpr.SUBINVENTORY_CODE IS NULL
        OR mil.segment1 IS NULL
        OR mil.segment2 IS NULL
        THEN 'N'
        ELSE 'W'
      END as STATUS,
      'OUT' as DIRECTION,
      TO_CHAR(zprh.RETURN_DATE, 'yyyy-MM-dd HH:mm:ss') as DOC_DATETIME,
      TO_CHAR(sysdate, 'yyyy-MM-dd HH:mm:ss') as LAST_UPDATE_DATE,
      TO_CHAR(sysdate, 'yyyy-MM-dd HH:mm:ss') as CREATION_DATE,
      'admin' as USER_NO,
      ZPR.RETURN_NO  || '-' || ZPR.RETURN_LINE_ID as ID,
      '' as ORDER_NO,
      '' as INV_SPLIT,
      ZPR.RETURN_NO as INVOICE_NO,
      TO_CHAR(TRUNC(zprh.RETURN_DATE), 'yyyy/mm/dd') as INVOICE_DATE,
      TO_CHAR(TRUNC(zprh.RETURN_DATE) + 1, 'yyyy/mm/dd') as EXP_SHIP_DATE,
      '' as CUST_NO,
      '' as DEPT,
      PV.VENDOR_NAME as CUST_NAME,
      zprh.SHIP_TO_ADDRESS as INVOICE_ADDRESS,
      '' as SHIP_TO_NO,
      zprh.SHIP_TO_ADDRESS as DELIVERY_ADDRESS,
      zprh.SHIP_TO_CONTACT as SHIP_TO_CONTACT,
      '' as SHIP_TO_PHONE,
      MSI.SEGMENT1 as ZT_PART_NO,
      '' as CUST_PART_NO,
      '' as CUSTOMER_PO,
      '' as SHIP_NOTICE,
      '' as SHIP_NOTES,
      'Approved' as STATUS1,
      PVSA.VENDOR_SITE_CODE as BRAND,
      zpr.QUANTITY as QUANTITY,
      NULL as UNIT_PRICE,
      NULL as AMOUNT,
      '' as CUST_PO,
      '' as CUST_PO2,
      '' as CUST_POLINE,
      '' as CUST_PN,
      '' as CUST_PN2,
      '' as ITEM_DESC,
      MSI.ATTRIBUTE1 as ITEM_MODE,
      '' as ORDER_LINE_MEMO,
      '' as UNIT_WEIGHT,
      '' as WEIGHT_UOM_CODE,
      zpr.SUBINVENTORY_CODE as FROM_SUBINVENTORY_CODE,
      mil.segment1 as SEGMENT1,
      mil.segment2 as SEGMENT2,
      '進貨退出單' as KIND,
      MSI.SEGMENT1 as SUPPLIER_PARTNO,
      '' as INV_AND_PAC,
      '' as CUST_PART_NO2,
      NVL(NVL(zpr.vendor_material_info,ZEN_GET_WMS_ITEM_F(MSI.SEGMENT1)),MSI.SEGMENT1) as PO_REMARK,
      PH.SEGMENT1||'-'||PL.LINE_NUM as ORI_PO_NO,
      zprh.RMA_NUM as RMA_NUMBER,
      '0' as ORD_TYPE,
      'TY' as QC_TYPE
     FROM 
       PO_VENDORS@PROD2 PV,
       PO_VENDOR_SITES_ALL@PROD2 PVSA,
       PO_HEADERS_ALL@PROD2 PH,
       PO_LINES_ALL@PROD2 PL,
      MTL_SYSTEM_ITEMS_B@PROD2 MSI,
      MTL_ITEM_LOCATIONS@PROD2 mil,
       ZEN_PO_RETURN_LINE_T@PROD2 zpr,
       ZEN_PO_RETURN_HEADER_T@PROD2 zprh
     WHERE 1=1
      AND zpr.ORGANIZATION_ID IN (169,209 ) 
      AND zpr.RETURN_NO = zprh.RETURN_NO 
      AND zpr.po_header_id =PH.PO_HEADER_ID
      AND PH.PO_HEADER_ID = PL.PO_HEADER_ID
      AND zpr.po_line_id = pl.po_line_id
       AND PH.VENDOR_ID = PV.VENDOR_ID
       AND PVSA.VENDOR_ID = PH.VENDOR_ID
       AND PVSA.VENDOR_SITE_ID = PH.VENDOR_SITE_ID
       AND ZPR.ITEM_ID = MSI.INVENTORY_ITEM_ID
       AND ZPR.ORGANIZATION_ID = MSI.ORGANIZATION_ID 
       AND PH.PO_HEADER_ID = PL.PO_HEADER_ID
       AND zpr.SUBINVENTORY_CODE  = '外存倉'
       AND zpr.LOCATOR_ID =  mil.INVENTORY_LOCATION_ID 
       AND (mil.segment1 like '%基通%' OR mil.segment2 like '%基通%')
       AND zprh.status ='Complete'
       AND zpr.status ='Open'  
       AND mil.attribute3='JIT'
        AND zpr.RETURN_NO = zprh.RETURN_NO
        AND trunc(zprh.creation_date) > to_date('20250501','yyyymmdd')
        AND NOT EXISTS(
            SELECT 1
            FROM ZEN_B2B_JSON_SO 
            WHERE 
                  ID = ZPR.RETURN_NO  || '-' || ZPR.RETURN_LINE_ID
            AND (STATUS = 
                CASE 
                WHEN PH.SEGMENT1||'-'||PL.LINE_NUM IS NULL
                OR zprh.RETURN_DATE IS NULL
                OR PV.VENDOR_NAME IS NULL
                OR zprh.SHIP_TO_ADDRESS IS NULL
                OR zprh.SHIP_TO_CONTACT IS NULL
                OR MSI.SEGMENT1 IS NULL
                OR PVSA.VENDOR_SITE_CODE IS NULL
                OR zpr.QUANTITY IS NULL
                OR MSI.ATTRIBUTE1 IS NULL
                OR zpr.SUBINVENTORY_CODE IS NULL
                OR mil.segment1 IS NULL
                OR mil.segment2 IS NULL
                THEN 'N'
                ELSE 'W'
                END OR STATUS = 'S')
        )
order by ID 
);

end;
