begin
EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_LANGUAGE= ''AMERICAN''';
insert into ZEN_B2B_JSON_SO_TMP (SEQ_ID,SENDER_CODE,RECEIVER_CODE,STATUS,DIRECTION,DOC_DATETIME,LAST_UPDATE_DATE,CREATION_DATE,USER_NO,ID,ORDER_NO,INV_SPLIT,INVOICE_NO,INVOICE_DATE,EXP_SHIP_DATE,CUST_NO,DEPT,CUST_NAME,INVOICE_ADDRESS,SHIP_TO_NO,DELIVERY_ADDRESS,SHIP_TO_CONTACT,SHIP_TO_PHONE,ZT_PART_NO,CUST_PART_NO,CUSTOMER_PO,SHIP_NOTICE,SHIP_NOTES,STATUS1,BRAND,QUANTITY,UNIT_PRICE,AMOUNT,CUST_PO,CUST_PO2,CUST_POLINE,CUST_PN,CUST_PN2,ITEM_DESC,ITEM_MODE,ORDER_LINE_MEMO,UNIT_WEIGHT,WEIGHT_UOM_CODE,FROM_SUBINVENTORY_CODE,SEGMENT1,SEGMENT2,KIND,SUPPLIER_PARTNO,INV_AND_PAC,CUST_PART_NO2,PO_REMARK,RMA_NUMBER,ORD_TYPE,QC_TYPE) 
select ZEN_B2B_JSON_SEQ.nextval,SENDER_CODE,RECEIVER_CODE,STATUS,DIRECTION,DOC_DATETIME,LAST_UPDATE_DATE,CREATION_DATE,USER_NO,ID,ORDER_NO,INV_SPLIT,INVOICE_NO,INVOICE_DATE,EXP_SHIP_DATE,CUST_NO,DEPT,CUST_NAME,INVOICE_ADDRESS,SHIP_TO_NO,DELIVERY_ADDRESS,SHIP_TO_CONTACT,SHIP_TO_PHONE,ZT_PART_NO,CUST_PART_NO,CUSTOMER_PO,SHIP_NOTICE,SHIP_NOTES,STATUS1,BRAND,QUANTITY,UNIT_PRICE,AMOUNT,CUST_PO,CUST_PO2,CUST_POLINE,CUST_PN,CUST_PN2,ITEM_DESC,ITEM_MODE,ORDER_LINE_MEMO,UNIT_WEIGHT,WEIGHT_UOM_CODE,FROM_SUBINVENTORY_CODE,SEGMENT1,SEGMENT2,KIND,SUPPLIER_PARTNO,INV_AND_PAC,CUST_PART_NO2,PO_REMARK,RMA_NUMBER,ORD_TYPE,QC_TYPE
from (
    SELECT
        'ZEN' as SENDER_CODE,
        'FEILIKS' as RECEIVER_CODE,
        CASE    
            WHEN ZMTH.HEADER_ID IS NULL -- ORDER_NO
            OR WS.INVOICENO IS NULL -- INVOICE_NO
            OR ZMTH.DATE_REQUIRED IS NULL -- INVOICE_DATE / EXP_SHIP_DATE
            OR dep.DEP_NAME IS NULL -- DEPT
            OR NVL(YC.ENAME,YC.CNAME) IS NULL -- CUST_NAME
            OR YC.CADDR IS NULL -- INVOICE_ADDRESS / DELIVERY_ADDRESS
            OR FU.USER_NAME IS NULL -- SHIP_TO_CONTACT
            OR YC.TELNO1 IS NULL -- SHIP_TO_PHONE
            OR MSIB.SEGMENT1 IS NULL -- ZT_PART_NO
            OR ZEN_GET_BRAND_ALIAS_F@zenprod(MSIB.ORGANIZATION_ID, ZMTL.INVENTORY_ITEM_ID ) IS NULL -- BRAND
            OR ZMTL.QUANTITY IS NULL -- QUANTITY
            OR NVL(ZMTL.ITEM_COST,0) IS NULL -- UNIT_PRICE
            OR ROUND(NVL(ZMTL.ITEM_COST,0) * ZMTL.QUANTITY,ZEN_CURRENCY_PRECISION@zenprod(ZMTL.TRANSACTIONAL_CURR_CODE)) IS NULL -- AMOUNT
            OR MSIB.ATTRIBUTE1 IS NULL -- ITEM_MODE
            OR ZMTL.FROM_SUBINVENTORY_CODE IS NULL -- FROM_SUBINVENTORY_CODE
            OR mil.segment1 IS NULL --SEGMENT1
            OR mil.segment2 IS NULL --SEGMENT2
            THEN 'N'
            ELSE 'W'
        END as STATUS,
        'OUT' as DIRECTION,
        TO_CHAR(ZMTH.DATE_REQUIRED, 'yyyy-MM-dd HH:mm:ss') as DOC_DATETIME,
        TO_CHAR(sysdate, 'yyyy-MM-dd HH:mm:ss') as LAST_UPDATE_DATE,
        TO_CHAR(sysdate, 'yyyy-MM-dd HH:mm:ss') as CREATION_DATE,
        'admin' as USER_NO,
        WS.INVOICENO || '-' || ZMTL.line_id as ID,
        ZMTH.HEADER_ID as ORDER_NO,
        '' as INV_SPLIT,
        WS.INVOICENO as INVOICE_NO,
        TO_CHAR(TRUNC(ZMTH.DATE_REQUIRED), 'yyyy/mm/dd') as INVOICE_DATE,
        TO_CHAR(TRUNC(ZMTH.DATE_REQUIRED) + 1, 'yyyy/mm/dd') as EXP_SHIP_DATE,
        '' as CUST_NO,
        dep.DEP_NAME as DEPT,
        NVL(YC.ENAME,YC.CNAME) as CUST_NAME,
        YC.CADDR as INVOICE_ADDRESS,
        '' as SHIP_TO_NO,
        YC.CADDR as DELIVERY_ADDRESS,
        FU.USER_NAME as SHIP_TO_CONTACT,
        YC.TELNO1 as SHIP_TO_PHONE,
        MSIB.SEGMENT1 as ZT_PART_NO,
        '' as CUST_PART_NO,
        '' as CUSTOMER_PO,
        '' as SHIP_NOTICE,
        '' as SHIP_NOTES,
        'Approved' as STATUS1,
        ZEN_GET_BRAND_ALIAS_F@zenprod(MSIB.ORGANIZATION_ID, ZMTL.INVENTORY_ITEM_ID ) as BRAND,
        ZMTL.QUANTITY as QUANTITY,
        TO_CHAR(NVL(ZMTL.ITEM_COST,0),'FM9999999999999990.99999999999999999999') as UNIT_PRICE,
        ROUND(NVL(ZMTL.ITEM_COST,0) * ZMTL.QUANTITY,ZEN_CURRENCY_PRECISION@zenprod(ZMTL.TRANSACTIONAL_CURR_CODE)) as AMOUNT,
        '' as CUST_PO,
        '' as CUST_PO2,
        '' as CUST_POLINE,
        '' as CUST_PN,
        '' as CUST_PN2,
        '' as ITEM_DESC,
        MSIB.ATTRIBUTE1 as ITEM_MODE,
        '' as ORDER_LINE_MEMO,
        '' as UNIT_WEIGHT,
        '' as WEIGHT_UOM_CODE,
        ZMTL.FROM_SUBINVENTORY_CODE as FROM_SUBINVENTORY_CODE,
        mil.segment1 as SEGMENT1,
        mil.segment2 as SEGMENT2,
        '移倉單' as KIND,
        MSIB.SEGMENT1 as SUPPLIER_PARTNO,
        '' as INV_AND_PAC,
        '' as CUST_PART_NO2,
        '' as PO_REMARK,
        '' as RMA_NUMBER,
        '0' as ORD_TYPE,
        'TY' as QC_TYPE 
    FROM 
        ZEN_MTL_TXN_REQUEST_HEADERS@zenprod ZMTH,
        ZEN_MTL_TXN_REQUEST_LINES@zenprod ZMTL,
        MTL_SYSTEM_ITEMS_B@zenprod MSIB,
        FND_USER@zenprod FU,
        MFG_LOOKUPS@zenprod MFGL,
        ZEN_ORGANIZATION_DEFINITIONS_V@zenprod OOD,
        apps.mtl_item_locations@zenprod mil,
        (
            SELECT DISTINCT 
                d.DEP_NAME,
                f.USER_NAME
            FROM 
                OA_DEPTALL@hr d
            JOIN 
                OA_USERALL@hr u ON d.DEP_NO = u.USER_DEPTNO
            JOIN 
                HR_EMPLOYEES@zenprod e ON u.USER_NO = e.ATTRIBUTE1
            JOIN 
                FND_USER@zenprod f ON e.EMPLOYEE_ID = f.EMPLOYEE_ID
        ) dep,
        zenhrnew.Y17_COMPANY@hr YC,
        zenwms.WMS_SHIPPING@hr WS,
        zenwms.WMS_SHIPPING_D@hr WSD
    WHERE ZMTH.HEADER_ID = ZMTL.HEADER_ID
        AND MSIB.INVENTORY_ITEM_ID = ZMTL.INVENTORY_ITEM_ID
        AND MFGL.LOOKUP_TYPE = 'MTL_TXN_REQUEST_STATUS'
        AND MFGL.LOOKUP_CODE = ZMTL.LINE_STATUS
        AND ZMTL.LINE_STATUS != 6
        AND ZMTH.HEADER_STATUS != 6
        AND ZMTH.CREATED_BY = FU.USER_ID
        AND MSIB.ORGANIZATION_ID = ZMTH.ORGANIZATION_ID
        AND ZMTH.ORGANIZATION_ID = OOD.ORGANIZATION_ID
        AND mil.organization_id(+) = ZMTL.organization_id
        AND mil.subinventory_code(+) = ZMTL.FROM_SUBINVENTORY_CODE
        AND mil.inventory_location_id(+) = ZMTL.from_LOCATOR_ID
        AND FU.USER_NAME = dep.USER_NAME
        AND ZMTH.ORGANIZATION_ID = YC.ORGANIZATION_ID
        AND WS.P_NO = WSD.P_NO
        AND WSD.DELIVERNO = TO_CHAR(ZMTH.HEADER_ID)
        AND ZMTL.FROM_SUBINVENTORY_CODE = '外存倉'
        AND (mil.segment1 like '%飛力達%' OR mil.segment2 like '%飛力達%')
        --AND TRUNC(ZMTH.DATE_REQUIRED) + 1 >= TRUNC(sysdate)  --for正式上線第一週(手動執行)
        AND TRUNC(ZMTH.DATE_REQUIRED) + 1 BETWEEN TRUNC(sysdate) - 1 AND TRUNC(sysdate) + 1 --for正式上線一週後(自動化)
        AND NOT EXISTS(
        SELECT 1
        FROM ZEN_B2B_JSON_SO 
        WHERE 
            ID = WS.INVOICENO || '-' || ZMTL.line_id
            AND (STATUS = 
                (CASE    
                    WHEN ZMTH.HEADER_ID IS NULL -- ORDER_NO
                    OR WS.INVOICENO IS NULL -- INVOICE_NO
                    OR ZMTH.DATE_REQUIRED IS NULL -- INVOICE_DATE / EXP_SHIP_DATE
                    OR dep.DEP_NAME IS NULL -- DEPT
                    OR NVL(YC.ENAME,YC.CNAME) IS NULL -- CUST_NAME
                    OR YC.CADDR IS NULL -- INVOICE_ADDRESS / DELIVERY_ADDRESS
                    OR FU.USER_NAME IS NULL -- SHIP_TO_CONTACT
                    OR YC.TELNO1 IS NULL -- SHIP_TO_PHONE
                    OR MSIB.SEGMENT1 IS NULL -- ZT_PART_NO
                    OR ZEN_GET_BRAND_ALIAS_F@zenprod(MSIB.ORGANIZATION_ID, ZMTL.INVENTORY_ITEM_ID ) IS NULL -- BRAND
                    OR ZMTL.QUANTITY IS NULL -- QUANTITY
                    OR NVL(ZMTL.ITEM_COST,0) IS NULL -- UNIT_PRICE
                    OR ROUND(NVL(ZMTL.ITEM_COST,0) * ZMTL.QUANTITY,ZEN_CURRENCY_PRECISION@zenprod(ZMTL.TRANSACTIONAL_CURR_CODE)) IS NULL -- UNIT_PRICE
                    OR MSIB.ATTRIBUTE1 IS NULL -- ITEM_MODE
                    OR ZMTL.FROM_SUBINVENTORY_CODE IS NULL -- FROM_SUBINVENTORY_CODE
                    OR mil.segment1 IS NULL --SEGMENT1
                    OR mil.segment2 IS NULL --SEGMENT2
                    THEN 'N'
                    ELSE 'W'
                END) OR STATUS = 'S')
        )
ORDER BY ORDER_NO, ID
);
end;